### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by domingo-valdes** [dagalloso/IIC3143-Crowdfunding#7]
Como se deprecian ls activos en un plazo de 15 años si en realidad se deprecian en 20? @TomasKings

**Comment by rfenzo** [comment]
Me extraña estimado, la [lectura de la semana pasada](http://www.sii.cl/preguntas_frecuentes/renta/001_002_2254.htm) resuelve, entre otras cosas, tu duda, estimado domingo. Saludos.
